# YAML Configuration for Build Job

# Note: This job is designed to build and publish Python artifacts using the specified tag name.
parameters:
  - name: build_version
    default: 9.9.9
  - name: artifact_name
    type: string

# Steps to be executed within the job.
steps:
  # Step 1: Install poetry.
  - script: |
      pip install poetry
    displayName: 'Install Poetry'

  # Step 2: Set the build version and update pyproject.toml.
  - script: |
      set BUILD_VERSION=${{parameters.build_version}}
      echo "Building version: %BUILD_VERSION%"
      poetry version $BUILD_VERSION
    displayName: 'Set Build Version'

  # Step 3: Install dependencies and build the wheel package.
  - script: |
      poetry install
      poetry build
    displayName: 'Build Package with Poetry'

  # Step 4: Publish the build artifacts to Azure Pipelines.
  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifacts to Azure Pipelines'
    inputs:
      PathtoPublish: dist
      ArtifactName: ${{parameters.artifact_name}}

# Note: This job is responsible for building a Python package and publishing it to Azure Pipelines.
# The job utilizes 'poetry' to manage dependencies and build the package, sets the build version, and publishes the resulting artifacts.
# The detailed docstring provides insights into each step's purpose and its contribution to the overall build process.
